### ISSUE TITLE
Mapper 没效果 并且有异常

### ISSUE THREAD

**Issue by wenerme** [go-ini/ini#10]
```
type Info struct{
	PackageName string
}

func t7() {
	i := &Info{}
	err := ini.MapToWithMapper(&i, ini.TitleUnderscore, []byte("packag_name=ini"))
	if err != nil { panic(err) }
	fmt.Printf("%#v\n",i)

	cfg, err := ini.Load("PACKAGE_NAME=ini")
	// ...
	info := new(Info)
	cfg.NameMapper = ini.AllCapsUnderscore
	info.PackageName="A"
	fmt.Printf("%#v\n",info)
	err = cfg.MapTo(info)
	fmt.Printf("%#v\n",info)
	// ...
}
```

输出为
```
&main.Info{PackageName:""}
&main.Info{PackageName:"A"}
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/go-ini/ini.(*Section).parseFieldName(0x0, 0x44bb970, 0xb, 0x0, 0x0, 0x0, 0x0)
	/Users/wener/go/src/github.com/go-ini/ini/struct.go:63 +0x5a
github.com/go-ini/ini.(*Section).mapTo(0x0, 0x4431fe0, 0xc208098520, 0xd9, 0x0, 0x0)
	/Users/wener/go/src/github.com/go-ini/ini/struct.go:157 +0x2b6
github.com/go-ini/ini.(*Section).MapTo(0x0, 0x438c3e0, 0xc208098520, 0x0, 0x0)
	/Users/wener/go/src/github.com/go-ini/ini/struct.go:199 +0x151
github.com/go-ini/ini.(*File).MapTo(0xc20804afc0, 0x438c3e0, 0xc208098520, 0x0, 0x0)
	/Users/wener/go/src/github.com/go-ini/ini/struct.go:204 +0x70
```

**Comment by Unknwon** [comment]
Hmm... OK, this is because you didn't use it right.

First of all, you ignore the error, which returns:

```
open PACKAGE_NAME=ini: no such file or directory
```

because: https://github.com/go-ini/ini#loading-from-data-sources

`[]byte` means data, `string` means file name.
