### ISSUE TITLE
isEmptyValue panic when struct filed has an omitempty tag

### ISSUE THREAD

**Issue by huaiyann** [go-ini/ini#108]
```
package main

import (
	"gopkg.in/ini.v1"
)

type TestSt struct {
	Empty EmptySt `ini:"empty_st,omitempty"`
}

type EmptySt struct {
	Str string `ini:"str"`
}

func main() {
	cfg := new(TestSt)
	cfgIni := ini.Empty()
	cfgIni.ReflectFrom(cfg)
}
```

It seems that in isEmptyValue, a struct is regarded as reflectTime

build with go1.8.1, the panic info is:

```
panic: interface conversion: interface {} is main.EmptySt, not time.Time

goroutine 1 [running]:
gopkg.in/ini%2ev1.isEmptyValue(0x10dbee0, 0xc4200742b0, 0x199, 0x9)
	/Users/huaiyann/codespace/xclib/src/gopkg.in/ini.v1/struct.go:413 +0x2f6
gopkg.in/ini%2ev1.(*Section).reflectFrom(0xc4200a0380, 0x10dbf60, 0xc4200742b0, 0x199, 0x0, 0x0)
	/Users/huaiyann/codespace/xclib/src/gopkg.in/ini.v1/struct.go:437 +0x96a
gopkg.in/ini%2ev1.(*Section).ReflectFrom(0xc4200a0380, 0x10cb8e0, 0xc4200742b0, 0xc4200a0380, 0x0)
	/Users/huaiyann/codespace/xclib/src/gopkg.in/ini.v1/struct.go:485 +0x20d
gopkg.in/ini%2ev1.(*File).ReflectFrom(0xc4200aa000, 0x10cb8e0, 0xc4200742b0, 0x1174b60, 0xc4200001a0)
	/Users/huaiyann/codespace/xclib/src/gopkg.in/ini.v1/struct.go:490 +0x5f
main.main()
	/Users/huaiyann/omitempty.go:18 +0x5f
```

**Comment by Unknwon** [comment]
Thanks for the feedback!

The patch has been pushed to `master`, you can update the package and test.

Be aware that regular struct will always return `false` for empty check. You need to use a pointer such as `*EmptySt`.

**Comment by yawaramin** [comment]
Another instance of this bug: https://github.com/go-ini/ini/blob/c787282c39ac1fc618827141a1f762240def08a3/struct.go#L388

**Comment by Unknwon** [comment]
@yawaramin please provide example code that causes problem.
