### ISSUE TITLE
hangs mapping a section to a struct if the section has a "." in the name

### ISSUE THREAD

**Issue by johnl** [go-ini/ini#11]
```
[foo.bar]
here = there
when = then
```

The above parses just fine and I can enumerate it using cfg.Sections, but when I map it using MapTo, it just hangs! Using no cpu or ram, just hangs.

Remove the dot from the section name, and it works just fine.

**Comment by johnl** [comment]
Got a test case to reproduce it. Causes the tests to error out with a deadlock:

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.RunTests(0x629650, 0x6c6580, 0x9, 0x9, 0xc20801e001)
	/home/john/.gvm/gos/go1.4/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20804e0f0, 0x6cf060)
	/home/john/.gvm/gos/go1.4/src/testing/testing.go:485 +0x6c
main.main()
	_/home/john/common/devel/brightbox/go-ini.git/_test/_testmain.go:78 +0x1d5

goroutine 13 [semacquire]:
sync.(*RWMutex).Lock(0xc208050784)
	/home/john/.gvm/gos/go1.4/src/sync/rwmutex.go:87 +0xa4
_/home/john/common/devel/brightbox/go-ini%2egit.(*File).NewSection(0xc208050780, 0xc20801e741, 0x9, 0x0, 0x0, 0x0)
	/home/john/common/devel/brightbox/go-ini.git/ini.go:636 +0x195
_/home/john/common/devel/brightbox/go-ini%2egit.(*File).Section(0xc208050780, 0xc20801e741, 0x9, 0x1)
	/home/john/common/devel/brightbox/go-ini.git/ini.go:683 +0x7d
_/home/john/common/devel/brightbox/go-ini%2egit.(*Section).GetKey(0xc20804e3c0, 0x5cfa90, 0x3, 0x0, 0x0, 0x0)
	/home/john/common/devel/brightbox/go-ini.git/ini.go:493 +0x18b
_/home/john/common/devel/brightbox/go-ini%2egit.(*Section).mapTo(0xc20804e3c0, 0x5b93a0, 0xc208034a00, 0xd9, 0x0, 0x0)
	/home/john/common/devel/brightbox/go-ini.git/struct.go:179 +0x5b4
_/home/john/common/devel/brightbox/go-ini%2egit.(*Section).MapTo(0xc20804e3c0, 0x54c120, 0xc208034a00, 0x0, 0x0)
	/home/john/common/devel/brightbox/go-ini.git/struct.go:199 +0x151
_/home/john/common/devel/brightbox/go-ini%2egit.func·052()
	/home/john/common/devel/brightbox/go-ini.git/struct_test.go:196 +0x2ce
github.com/smartystreets/goconvey/convey.func·006(0x7f635cee8eb8, 0xc208050720)
	/home/john/.gvm/pkgsets/go1.4/global/src/github.com/smartystreets/goconvey/convey/discovery.go:80 +0x22
github.com/smartystreets/goconvey/convey.(*context).conveyInner(0xc208050720, 0x60cab0, 0x29, 0xc20800b350)
	/home/john/.gvm/pkgsets/go1.4/global/src/github.com/smartystreets/goconvey/convey/context.go:261 +0x27f
github.com/smartystreets/goconvey/convey.func·001()
	/home/john/.gvm/pkgsets/go1.4/global/src/github.com/smartystreets/goconvey/convey/context.go:110 +0x157
github.com/jtolds/gls._m(0x0, 0xc20801e660)
	/home/john/.gvm/pkgsets/go1.4/global/src/github.com/jtolds/gls/stack_tags.go:70 +0x32
github.com/jtolds/gls.markS(0x0, 0xc20801e660)
	/home/john/.gvm/pkgsets/go1.4/global/src/github.com/jtolds/gls/stack_tags.go:21 +0x32
github.com/jtolds/gls.addStackTag(0x0, 0xc20801e660)
	/home/john/.gvm/pkgsets/go1.4/global/src/github.com/jtolds/gls/stack_tags.go:18 +0x3e
github.com/jtolds/gls.(*ContextManager).SetValues(0xc20801e060, 0xc2080885a0, 0xc20801e660)
	/home/john/.gvm/pkgsets/go1.4/global/src/github.com/jtolds/gls/context.go:98 +0x503
github.com/smartystreets/goconvey/convey.rootConvey(0xc208083f40, 0x3, 0x3)
	/home/john/.gvm/pkgsets/go1.4/global/src/github.com/smartystreets/goconvey/convey/context.go:113 +0x486
github.com/smartystreets/goconvey/convey.Convey(0xc208083f40, 0x3, 0x3)
	/home/john/.gvm/pkgsets/go1.4/global/src/github.com/smartystreets/goconvey/convey/doc.go:75 +0x4c
_/home/john/common/devel/brightbox/go-ini%2egit.Test_NameWithDots(0xc2080661b0)
	/home/john/common/devel/brightbox/go-ini.git/struct_test.go:197 +0x157
testing.tRunner(0xc2080661b0, 0x6c6640)
	/home/john/.gvm/gos/go1.4/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/home/john/.gvm/gos/go1.4/src/testing/testing.go:555 +0xa8b
exit status 2
FAIL	_/home/john/common/devel/brightbox/go-ini.git	0.019s

```

**Comment by johnl** [comment]
workaround is to turn off block mode (which presumably stops using the mutex so avoids a deadlock):

```
cfg.BlockMode = false
```

**Comment by Unknwon** [comment]
Thanks your feedback, I'm working on it!

**Comment by Unknwon** [comment]
Hi! I've reproduced the deadlock and pushed fix code, please help test again! Thanks!

**Comment by johnl** [comment]
yep, confirmed fixed. Thanks! Feel free to merge my test case, so it never reoccurs :)

**Comment by Unknwon** [comment]
Yeah, actually I simply did: https://github.com/go-ini/ini/commit/a2b4016f46d54039188599eb8e9abde61afd2f4c#diff-9055dacae126fe133b9eeff1ee972944R62 :beer:
