### ISSUE TITLE
用strings.NewReader或者bytes.NewReader不能正确解析

### ISSUE THREAD

**Issue by tietang** [go-ini/ini#118]
code:

```golang
r := strings.NewReader(`

		[x1]
        k1=true
        k2:false
        k3=t
        k4=T
        k5=1
        k6=f
        k7=F
        k8=0
        k9=t0
        k10=12
        k11=-12

        `)
  
    cfg, err := ini.Load(r)
    fmt.Println(err)

    ss := cfg.Sections()

```
错误信息：

```

error parsing data source: unknown type '&{

		[x1]
        k1=true
        k2:false
        k3=t
        k4=T
        k5=1
        k6=f
        k7=F
        k8=0
        k9=t0
        k10=12
        k11=-12

         %!s(int64=0) %!s(int=-1)}'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x10b6eb6]

goroutine 1 [running]:
gopkg.in/ini%2ev1.(*File).Sections(0x0, 0x1, 0x1, 0xf5)
	/Users/tietang/java/gothird/src/gopkg.in/ini.v1/ini.go:691 +0x26
main.main()
	/Users/tietang/my/gitcode/r_app/src/demo/cb/ini2.go:53 +0x122
exit status 2

```

**Comment by tietang** [comment]
已经解决，版本未更新未最新的。sorry
