### ISSUE TITLE
GetSection fails with nil pointer dereference

### ISSUE THREAD

**Issue by rcpnair** [go-ini/ini#211]
**Problem**
File.GetSection fails with invalid memory address or nil pointer dereference instead of returning error
```
func doesSectionExist(cfg *ini.File, section string) bool {
	_, err := cfg.GetSection(section)

	if err != nil {
		return false
	}
	return true
}

```
_Error_
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1 pc=0x530c32]

goroutine 7 [running]:
testing.tRunner.func1(0xc0000ca100)
	/src/testing/testing.go:874 +0x3aa
panic(0x711c00, 0x9dcc50)
	/src/runtime/panic.go:679 +0x1c0
gopkg.in/ini%2ev1.(*File).GetSection(0x0, 0x774b88, 0x3, 0x0, 0x0, 0x0)
	gopkg.in/ini.v1@v1.48.0/file.go:116 +0x72
```
**How to reproduce?**
Declare an empty file object and call GetSection("dummy")
```
var f *ini.File
_err := f.GetSection("dummy")
```

**Comment by rcpnair** [comment]
Adding a nil pointer check to the function helped though
```
	if cfg == nil {
		return false
	}
```

**Comment by unknwon** [comment]
Hi, thanks for the feedback, but I think this is exactly what should happen, because it is `nil` in your code.
