### ISSUE TITLE
How do I avoid having an unnamed section at the top?

### ISSUE THREAD

**Issue by synedra** [go-ini/ini#64]
I'm reading an INI file that has no unnamed section, but it's writing out an unnamed section at the top (same as the "default" section).  How can I avoid this?

**Comment by synedra** [comment]
Note that this causes issues with INI parsers from other languages:
Traceback (most recent call last):
  File "diagnostic_tools.py", line 32, in <module>
    config = EdgeGridConfig({},section_name)
  File "/Users/khunter/Dropbox/src/production/api-kickstart/examples/python/config.py", line 79, in __init__
    config.readfp(open(arguments["config_file"]))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /Users/khunter/.edgerc, line: 1
'client_secret = YyCch9uU+ahJ55KhuE6n/YJIygR7pJDQx/XzlT3OnnI=\n'

**Comment by synedra** [comment]
Still debugging - it looks like it's not grabbing the top value in the config file it's pulling.  I'll look some more.

**Comment by synedra** [comment]
And now it's working... :-)
